language: objective-c
osx_image: xcode7.2
xcode_workspace: PathfinderCC.xcworkspace
xcode_scheme: PathfinderCCTravis
xcode_sdk: iphonesimulator9.2
script:
  - xcodebuild test -workspace PathfinderCC.xcworkspace -scheme PathfinderCCTravis -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.2'
after_success:
- bash <(curl -s https://codecov.io/bash)
before_script:
- pod install
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/profile/PathfinderCCAdhoc.mobileprovision.enc -d -a -out scripts/profile/TravisExample_Ad_Hoc.mobileprovision
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.cer.enc -d -a -out scripts/certs/dist.cer
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.p12.enc -d -a -out scripts/certs/dist.p12
env:
  global:
  - secure: gvWBWtaThYNKalIBkPq6uGJLbFwhHT589Y0/jeeREEHWd6GQhjnxjFZR2paNNbsyEkgKUIE9yeIvGuiYlzmVBmBajSuLVQUPKzxhccG5vo8Jw47DpOABG7Qov6og3RzbI56PFO/XIyg5nEvkbay6MbLEVsauqZrJu9GMAf1gpFg=
  - APP_NAME="PathfinderCC"
  - 'DEVELOPER_NAME="iPhone Distribution: Dave Post (37CAHGRH45)"'
  - PROFILE_NAME="PathfindeCCAdhoc"
  - secure: EeUCAfDEpI4gtNoQlauDl+M0zKl371qmfFoIzMngXuO7Ly6RiflPPxChAI7D0nLJn72m0JrDrbQGC1vLrHeebnPdDlHQ4xEL9Wzg+aVdyab0QsJSG4dPf0UVaTqBIpWiPlbg1GvNrgiE7n99PEHSTDBJzjirS0TyiXfp3iwRiG4=
