language: objective-c
xcode_workspace: PathfinderCC.xcworkspace
xcode_scheme: PathfinderCC

before_script:
  - sudo easy_install cpp-coveralls
  
before_install: 
  - gem install cocoapods

script:
  - xctool -workspace PathfinderCC.xcworkspace -scheme "PathfinderCC" test -sdk iphonesimulator -arch i386
  - oclint-json-compilation-database

after_success:
      - ./coveralls.rb --extension m
