language: objective-c
xcode_workspace: PathfinderCC.xcworkspace
xcode_scheme: PathfinderCC

before_script:
  - sudo easy_install cpp-coveralls
  
before_install: 
  - gem install cocoapods

after_success:
      - ./coveralls.rb --extension m
