language: objective-c
xcode_workspace: PathfinderCC.xcworkspace
xcode_scheme: PathfinderCC

before_script:
  - sudo easy_install cpp-coveralls
  - brew update
  - brew upgrade xctool
  
before_install: 
  - gem install cocoapods
  
script:
  - xctool -workspace PathfinderCC.xcworkspace -scheme PathfinderCC -sdk iphonesimulator -arch i386 build test

after_success:
      - ./coveralls.rb --extension m
