language: objective-c
xcode_workspace: PathfinderCC.xcworkspace
xcode_scheme: PathfinderCC

before_script:
  - sudo easy_install cpp-coveralls

script:
  - xctool -workspace PathfinderCC.xcworkspace -scheme "PathfinderCC" build test -sdk iphonesimulator -arch i386

after_success:
      - ./coveralls.rb --extension m