language: objective-c
xcode_workspace: PathfinderCC.xcworkspace
xcode_scheme: PathfinderCC

before_script:
  - sudo easy_install cpp-coveralls

script:
  - xctool -project PathfinderCC.xcodeproj -scheme "PathfinderCC" build test -sdk iphonesimulator

after_success:
      - ./coveralls.rb --extension m