language: objective-c
osx_image: xcode7.2
xcode_workspace: PathfinderCC.xcworkspace
xcode_scheme: PathfinderCC
before_script:
  - pod install
  - sudo easy_install cpp-coveralls
  
after_success:
  - ./coveralls.rb --extension m
