language: objective-c
before_script:
  - sudo easy_install cpp-coveralls
  - brew update
  - brew upgrade xctool
  
before_install: 
  - gem install cocoapods
  
script:
  - xctool -project PathfinderCC.xcodeproj -sdk iphonesimulator -scheme PathfinderCC -arch i386 build test
  
after_success:
      - ./coveralls.rb --extension m
